# Generated by Django 5.1.3 on 2025-03-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_service', '0002_alter_carrito_table_alter_carritoitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='format',
            field=models.CharField(choices=[('digital', 'Digital'), ('cd', 'CD'), ('vinilo', 'Vinilo'), ('cassette', 'Cassette')], default='cd', max_length=20),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
