# Generated by Django 5.1.3 on 2025-03-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table='pedidos',
        ),
        migrations.AlterModelTable(
            name='pedidoitem',
            table='pedidos_items',
        ),
    ]
