# Generated by Django 5.1.3 on 2024-11-25 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categoria_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimensiones',
            name='product',
        ),
    ]
