# Generated by Django 5.1.3 on 2024-11-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_dimensiones_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='informacion_envio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='informacion_garantia',
        ),
    ]
