# Generated by Django 5.1.4 on 2024-12-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_reseña_calificacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseña',
            new_name='Resena'
        ),
    ]
