version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
    networks:
      - ecommerce-network
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
    networks:
      - ecommerce-network
  order-service:

    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
    networks:
      - ecommerce-network

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
    networks:
      - ecommerce-network

  shopping-cart-service:
    build:
      context: ./shopping-cart-service
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
    networks:
      - ecommerce-network

  postgres:

    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  nginx:
    image: nginx:1.19
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
      - shopping-cart-service
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres-data:
