# Generated by Django 5.1.4 on 2024-12-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_resena_producto'),
        ('products', '0008_alter_resena_producto_alter_usuario_email'),
    ]

    operations = [
    ]
