# Generated by Django 5.1.3 on 2025-03-11 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profundidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stock', models.PositiveIntegerField()),
                ('marca', models.CharField(max_length=100)),
                ('imagen', models.URLField(max_length=500)),
                ('estado_disponibilidad', models.CharField(max_length=50)),
                ('politica_devolucion', models.CharField(max_length=200)),
                ('cantidad_minima', models.PositiveIntegerField()),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='product_service.categoria')),
                ('dimensiones', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='product_service.dimensiones')),
            ],
        ),
    ]
