# Generated by Django 5.1.3 on 2024-12-05 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_merge_20241204_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='dimensiones',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='products.dimensiones'),
        ),
    ]
