<<<<<<< HEAD
# Generated by Django 5.1.3 on 2025-02-03 01:00
=======
# Generated by Django 5.1.3 on 2024-12-05 16:41
>>>>>>> 22fe05a30cb04ed03dcc498f1abbc8cd679e40de

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_producto_dimensiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='usuario',
<<<<<<< HEAD
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
=======
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
>>>>>>> 22fe05a30cb04ed03dcc498f1abbc8cd679e40de
        ),
    ]
