# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pokemon_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_home(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        MainWindow.setStyleSheet("QMainWindow {\n"
                                 "    background-color: #dc2626;\n"
                                 "}\n"
                                 "QWidget#centralwidget {\n"
                                 "    background-color: #dc2626;\n"
                                 "}\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # Title Bar
        self.titleBarFrame = QtWidgets.QFrame(self.centralwidget)
        self.titleBarFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.titleBarFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titleBarFrame.setObjectName("titleBarFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titleBarFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        # Title Bar Buttons
        self.blueButton = QtWidgets.QPushButton(self.titleBarFrame)
        self.blueButton.setMinimumSize(QtCore.QSize(16, 16))
        self.blueButton.setMaximumSize(QtCore.QSize(16, 16))
        self.blueButton.setStyleSheet("QPushButton {\n"
                                      "    background-color: #3b82f6;\n"
                                      "    border-radius: 8px;\n"
                                      "    border: none;\n"
                                      "}\n"
                                      "")
        self.blueButton.setObjectName("blueButton")
        self.horizontalLayout.addWidget(self.blueButton)
        
        self.yellowButton = QtWidgets.QPushButton(self.titleBarFrame)
        self.yellowButton.setMinimumSize(QtCore.QSize(16, 16))
        self.yellowButton.setMaximumSize(QtCore.QSize(16, 16))
        self.yellowButton.setStyleSheet("QPushButton {\n"
                                        "    background-color: #facc15;\n"
                                        "    border-radius: 8px;\n"
                                        "    border: none;\n"
                                        "}\n"
                                        "")
        self.yellowButton.setObjectName("yellowButton")
        self.horizontalLayout.addWidget(self.yellowButton)
        
        self.greenButton = QtWidgets.QPushButton(self.titleBarFrame)
        self.greenButton.setMinimumSize(QtCore.QSize(16, 16))
        self.greenButton.setMaximumSize(QtCore.QSize(16, 16))
        self.greenButton.setStyleSheet("QPushButton {\n"
                                       "    background-color: #22c55e;\n"
                                       "    border-radius: 8px;\n"
                                       "    border: none;\n"
                                       "}\n"
                                       "")
        self.greenButton.setObjectName("greenButton")
        self.horizontalLayout.addWidget(self.greenButton)
        
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.titleBarFrame)
        
        # Image Frame
        self.imageFrame = QtWidgets.QFrame(self.centralwidget)
        self.imageFrame.setStyleSheet("QFrame {\n"
                                      "    background-color: black;\n"
                                      "    border-radius: 8px;\n"
                                      "    padding: 10px;\n"
                                      "}\n"
                                      "")
        self.imageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageFrame.setObjectName("imageFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.imageFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        # Pokémon Image
        self.pokemonImage = QtWidgets.QLabel(self.imageFrame)
        self.pokemonImage.setMinimumSize(QtCore.QSize(0, 200))
        self.pokemonImage.setStyleSheet("QLabel {\n"
                                        "    background-color: transparent;\n"
                                        "}\n"
                                        "")
        self.pokemonImage.setText("")
        self.pokemonImage.setPixmap(QtGui.QPixmap("pokemon.png"))
        self.pokemonImage.setScaledContents(True)
        self.pokemonImage.setAlignment(QtCore.Qt.AlignCenter)
        self.pokemonImage.setObjectName("pokemonImage")
        self.verticalLayout_2.addWidget(self.pokemonImage)
        self.verticalLayout.addWidget(self.imageFrame)
        
        # Info Frame
        self.infoFrame = QtWidgets.QFrame(self.centralwidget)
        self.infoFrame.setStyleSheet("QFrame {\n"
                                     "    background-color: #22c55e;\n"
                                     "    border-radius: 8px;\n"
                                     "    padding: 10px;\n"
                                     "}\n"
                                     "QLabel {\n"
                                     "    color: black;\n"
                                     "    font-size: 14px;\n"
                                     "}\n"
                                     "")
        self.infoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoFrame.setObjectName("infoFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.infoFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        # Info Labels (empty text)
        self.nameLabel = QtWidgets.QLabel(self.infoFrame)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout_3.addWidget(self.nameLabel)
        
        self.abilitiesLabel = QtWidgets.QLabel(self.infoFrame)
        self.abilitiesLabel.setObjectName("abilitiesLabel")
        self.verticalLayout_3.addWidget(self.abilitiesLabel)
        
        self.ability1Label = QtWidgets.QLabel(self.infoFrame)
        self.ability1Label.setObjectName("ability1Label")
        self.verticalLayout_3.addWidget(self.ability1Label)
        
        self.ability2Label = QtWidgets.QLabel(self.infoFrame)
        self.ability2Label.setObjectName("ability2Label")
        self.verticalLayout_3.addWidget(self.ability2Label)
        
        self.heightLabel = QtWidgets.QLabel(self.infoFrame)
        self.heightLabel.setObjectName("heightLabel")
        self.verticalLayout_3.addWidget(self.heightLabel)
        
        self.verticalLayout.addWidget(self.infoFrame)
        
        # Navigation Frame
        self.navigationFrame = QtWidgets.QFrame(self.centralwidget)
        self.navigationFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.navigationFrame.setObjectName("navigationFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.navigationFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        
        # Previous Button
        self.prevButton = QtWidgets.QPushButton(self.navigationFrame)
        self.prevButton.setMinimumSize(QtCore.QSize(40, 40))
        self.prevButton.setStyleSheet("QPushButton {\n"
                                      "    background-color: black;\n"
                                      "    border: none;\n"
                                      "    border-radius: 4px;\n"
                                      "}\n"
                                      "")
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout_2.addWidget(self.prevButton)
        
        # Next Button
        self.nextButton = QtWidgets.QPushButton(self.navigationFrame)
        self.nextButton.setMinimumSize(QtCore.QSize(40, 40))
        self.nextButton.setStyleSheet("QPushButton {\n"
                                      "    background-color: black;\n"
                                      "    border: none;\n"
                                      "    border-radius: 4px;\n"
                                      "}\n"
                                      "")
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_2.addWidget(self.nextButton)
        
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        
        self.verticalLayout.addWidget(self.navigationFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pokémon Info"))
        
        # Empty fields to be filled by the code
        self.nameLabel.setText(_translate("MainWindow", ""))
        self.abilitiesLabel.setText(_translate("MainWindow", ""))
        self.ability1Label.setText(_translate("MainWindow", ""))
        self.ability2Label.setText(_translate("MainWindow", ""))
        self.heightLabel.setText(_translate("MainWindow", ""))
        
        self.prevButton.setText(_translate("MainWindow", "▲"))
        self.nextButton.setText(_translate("MainWindow", "▼"))
