# Generated by Django 5.1.3 on 2025-03-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
