# Generated by Django 5.1.3 on 2025-03-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
