export const musicData = {
  albums: [
    {
      id: 1,
      title: "Midnight Echoes",
      artist: "Luna Waves",
      genre: "indie",
      price: 9.99,
      releaseDate: "2023-05-15",
      cover: "/placeholder.svg?height=500&width=500",
      description:
        "A dreamy collection of indie tracks that blend acoustic and electronic elements. Perfect for late-night listening sessions.",
      tracks: [
        { title: "Moonlit Path", duration: "3:45" },
        { title: "Whispers in the Dark", duration: "4:12" },
        { title: "Starry Skies", duration: "3:58" },
        { title: "Echo Chamber", duration: "5:21" },
        { title: "Midnight Drive", duration: "4:07" },
        { title: "Lost in Dreams", duration: "3:36" },
        { title: "Silent Shadows", duration: "4:52" },
        { title: "Dawn Approaches", duration: "3:49" },
      ],
      reviews: [
        {
          user: "MusicLover42",
          rating: 5,
          date: "2023-06-10",
          comment: "Absolutely stunning album! The production is flawless and the melodies are hauntingly beautiful.",
        },
        {
          user: "NightOwl",
          rating: 4,
          date: "2023-06-22",
          comment: "Perfect for late night listening. 'Midnight Drive' is my favorite track.",
        },
      ],
    },
    {
      id: 2,
      title: "Electric Pulse",
      artist: "Neon Circuits",
      genre: "electronic",
      price: 8.99,
      releaseDate: "2023-03-21",
      cover: "/placeholder.svg?height=500&width=500",
      description:
        "A high-energy electronic album featuring pulsating beats and futuristic synths. Designed to get you moving.",
      tracks: [
        { title: "Power On", duration: "3:21" },
        { title: "Digital Dreams", duration: "4:45" },
        { title: "Neon Lights", duration: "3:56" },
        { title: "Circuit Breaker", duration: "5:12" },
        { title: "Voltage", duration: "4:33" },
        { title: "Binary Code", duration: "3:48" },
        { title: "Electric City", duration: "4:27" },
        { title: "Power Down", duration: "6:15" },
      ],
      reviews: [
        {
          user: "DanceFloorKing",
          rating: 5,
          date: "2023-04-05",
          comment: "This album is fire! Haven't stopped dancing since I got it.",
        },
        {
          user: "BeatMaster",
          rating: 4,
          date: "2023-04-12",
          comment: "Solid electronic production. 'Circuit Breaker' is an absolute banger!",
        },
      ],
    },
    {
      id: 3,
      title: "Soulful Journey",
      artist: "Melody Rivers",
      genre: "soul",
      price: 10.99,
      releaseDate: "2023-02-10",
      cover: "/placeholder.svg?height=500&width=500",
      description:
        "A heartfelt soul album with powerful vocals and rich instrumentation. Takes you on an emotional journey from start to finish.",
      tracks: [
        { title: "Heart's Desire", duration: "4:12" },
        { title: "River of Emotions", duration: "5:23" },
        { title: "Soul Searching", duration: "4:56" },
        { title: "Love's Embrace", duration: "3:45" },
        { title: "Healing Waters", duration: "5:32" },
        { title: "Inner Light", duration: "4:18" },
        { title: "Journey Home", duration: "6:07" },
        { title: "Peaceful Mind", duration: "4:52" },
      ],
      reviews: [
        {
          user: "SoulSister",
          rating: 5,
          date: "2023-02-28",
          comment: "Melody's voice is like honey! This album touches my soul deeply.",
        },
        {
          user: "MusicCritic101",
          rating: 4,
          date: "2023-03-15",
          comment: "A beautiful collection of soulful tracks. The instrumentation is top-notch.",
        },
      ],
    },
    {
      id: 4,
      title: "Urban Rhythms",
      artist: "Street Poets",
      genre: "hip-hop",
      price: 9.49,
      releaseDate: "2023-04-05",
      cover: "/placeholder.svg?height=500&width=500",
      description:
        "A hard-hitting hip-hop album with sharp lyrics and innovative beats. Tells stories of urban life and personal struggles.",
      tracks: [
        { title: "City Lights", duration: "3:45" },
        { title: "Concrete Jungle", duration: "4:21" },
        { title: "Street Knowledge", duration: "3:56" },
        { title: "Hustle Hard", duration: "4:12" },
        { title: "Urban Tales", duration: "5:03" },
        { title: "Midnight in the City", duration: "3:48" },
        { title: "Rise Up", duration: "4:27" },
        { title: "New Dawn", duration: "5:15" },
      ],
      reviews: [
        {
          user: "HipHopHead",
          rating: 5,
          date: "2023-04-20",
          comment: "These beats are fire and the lyrics are so real. Street Poets never disappoint!",
        },
        {
          user: "RhymeMaster",
          rating: 4,
          date: "2023-05-02",
          comment: "Solid album with great production. 'Hustle Hard' is on repeat!",
        },
      ],
    },
    {
      id: 5,
      title: "Guitar Dreams",
      artist: "Acoustic Wanderers",
      genre: "folk",
      price: 8.49,
      releaseDate: "2023-01-15",
      cover: "/placeholder.svg?height=500&width=500",
      description:
        "A gentle folk album featuring intricate guitar work and heartfelt vocals. Perfect for quiet evenings and peaceful moments.",
      tracks: [
        { title: "Mountain Trail", duration: "4:12" },
        { title: "Wooden Cabin", duration: "3:56" },
        { title: "River's Flow", duration: "5:23" },
        { title: "Forest Whispers", duration: "4:45" },
        { title: "Campfire Tales", duration: "6:12" },
        { title: "Autumn Leaves", duration: "3:48" },
        { title: "Wanderer's Path", duration: "4:32" },
        { title: "Home Again", duration: "5:15" },
      ],
      reviews: [
        {
          user: "AcousticLover",
          rating: 5,
          date: "2023-02-01",
          comment: "Such beautiful guitar work! This album is like a warm hug.",
        },
        {
          user: "FolkFan",
          rating: 4,
          date: "2023-02-15",
          comment: "Soothing and authentic folk music. Perfect for relaxing evenings.",
        },
      ],
    },
    {
      id: 6,
      title: "Rock Revolution",
      artist: "Electric Rebels",
      genre: "rock",
      price: 9.99,
      releaseDate: "2023-06-01",
      cover: "/placeholder.svg?height=500&width=500",
      description:
        "A powerful rock album with driving guitars and anthemic choruses. Captures the rebellious spirit of classic rock with a modern twist.",
      tracks: [
        { title: "Revolution Calling", duration: "4:21" },
        { title: "Electric Dreams", duration: "3:56" },
        { title: "Rebel Heart", duration: "5:12" },
        { title: "Breaking Free", duration: "4:45" },
        { title: "Guitar Hero", duration: "6:23" },
        { title: "Rock Anthem", duration: "4:18" },
        { title: "Freedom Fighters", duration: "5:32" },
        { title: "Last Stand", duration: "7:15" },
      ],
      reviews: [
        {
          user: "RockNRollForever",
          rating: 5,
          date: "2023-06-15",
          comment: "This album rocks! Reminds me of the golden age of rock but with a fresh sound.",
        },
        {
          user: "GuitarGod",
          rating: 4,
          date: "2023-06-22",
          comment: "Killer guitar solos and powerful vocals. 'Guitar Hero' is an instant classic!",
        },
      ],
    },
    {
      id: 7,
      title: "Jazz Nights",
      artist: "Smooth Quartet",
      genre: "jazz",
      price: 11.99,
      releaseDate: "2023-02-28",
      cover: "/placeholder.svg?height=500&width=500",
      description:
        "A sophisticated jazz album featuring smooth improvisations and classic jazz standards. Perfect for elegant evenings and sophisticated gatherings.",
      tracks: [
        { title: "Midnight Blue", duration: "5:45" },
        { title: "Saxophone Dreams", duration: "6:23" },
        { title: "Piano Interlude", duration: "4:12" },
        { title: "Smooth Sailing", duration: "7:32" },
        { title: "City Lights", duration: "5:56" },
        { title: "Jazz Club", duration: "6:48" },
        { title: "Late Night Conversation", duration: "8:15" },
        { title: "Last Call", duration: "4:52" },
      ],
      reviews: [
        {
          user: "JazzCat",
          rating: 5,
          date: "2023-03-10",
          comment: "Exquisite jazz compositions! The saxophone solos are breathtaking.",
        },
        {
          user: "MusicProfessor",
          rating: 4,
          date: "2023-03-25",
          comment: "A well-crafted jazz album with excellent musicianship throughout.",
        },
      ],
    },
    {
      id: 8,
      title: "Classical Masterpieces",
      artist: "Symphony Orchestra",
      genre: "classical",
      price: 12.99,
      releaseDate: "2023-01-05",
      cover: "/placeholder.svg?height=500&width=500",
      description:
        "A collection of timeless classical pieces performed by a world-class orchestra. Features works by Mozart, Beethoven, and Bach.",
      tracks: [
        { title: "Symphony No. 5", duration: "7:45" },
        { title: "Moonlight Sonata", duration: "6:23" },
        { title: "Four Seasons: Spring", duration: "10:12" },
        { title: "Canon in D", duration: "5:32" },
        { title: "Für Elise", duration: "3:56" },
        { title: "Air on G String", duration: "5:48" },
        { title: "Ode to Joy", duration: "8:15" },
        { title: "Swan Lake Theme", duration: "6:52" },
      ],
      reviews: [
        {
          user: "ClassicalFan",
          rating: 5,
          date: "2023-01-20",
          comment: "Magnificent performances of these timeless pieces. The recording quality is superb.",
        },
        {
          user: "MusicScholar",
          rating: 4,
          date: "2023-02-05",
          comment: "A wonderful collection of classical favorites performed with precision and emotion.",
        },
      ],
    },
    {
      id: 9,
      title: "Chill Vibes",
      artist: "Lofi Beats",
      genre: "lofi",
      price: 7.99,
      releaseDate: "2023-05-01",
      cover: "/placeholder.svg?height=500&width=500",
      description:
        "A relaxing collection of lofi hip hop beats perfect for studying, working, or unwinding. Mellow rhythms and soothing melodies throughout.",
      tracks: [
        { title: "Study Session", duration: "3:45" },
        { title: "Rainy Day", duration: "4:12" },
        { title: "Coffee Shop", duration: "3:56" },
        { title: "Late Night Thoughts", duration: "5:23" },
        { title: "Gentle Waves", duration: "4:32" },
        { title: "Urban Sunset", duration: "3:48" },
        { title: "Peaceful Mind", duration: "4:15" },
        { title: "Dreaming", duration: "5:52" },
      ],
      reviews: [
        {
          user: "ChillStudent",
          rating: 5,
          date: "2023-05-15",
          comment: "Perfect for my study sessions! These beats help me focus without being distracting.",
        },
        {
          user: "LofiLover",
          rating: 4,
          date: "2023-05-28",
          comment: "Great collection of chill beats. 'Rainy Day' is my go-to track for relaxing.",
        },
      ],
    },
    {
      id: 10,
      title: "Country Roads",
      artist: "Southern Comfort",
      genre: "country",
      price: 8.99,
      releaseDate: "2023-03-15",
      cover: "/placeholder.svg?height=500&width=500",
      description:
        "A heartfelt country album with stories of love, loss, and life on the road. Features twangy guitars, soulful vocals, and authentic country spirit.",
      tracks: [
        { title: "Dusty Highway", duration: "3:56" },
        { title: "Small Town Heart", duration: "4:23" },
        { title: "Pickup Truck", duration: "3:45" },
        { title: "Country Sunrise", duration: "5:12" },
        { title: "Whiskey Nights", duration: "4:32" },
        { title: "Back Home", duration: "3:48" },
        { title: "Southern Skies", duration: "4:15" },
        { title: "Forever Country", duration: "5:23" },
      ],
      reviews: [
        {
          user: "CountryGirl",
          rating: 5,
          date: "2023-04-01",
          comment: "This album speaks to my soul! Authentic country music at its finest.",
        },
        {
          user: "SouthernBoy",
          rating: 4,
          date: "2023-04-15",
          comment: "Great storytelling and beautiful melodies. 'Small Town Heart' brings tears to my eyes.",
        },
      ],
    },
    {
      id: 11,
      title: "Reggae Sunshine",
      artist: "Island Rhythms",
      genre: "reggae",
      price: 9.49,
      releaseDate: "2023-04-20",
      cover: "/placeholder.svg?height=500&width=500",
      description:
        "A vibrant reggae album with uplifting messages and infectious rhythms. Brings the sunshine and positive vibes of the islands to your speakers.",
      tracks: [
        { title: "Island Life", duration: "4:23" },
        { title: "Sunshine Reggae", duration: "5:12" },
        { title: "One Love", duration: "4:56" },
        { title: "Beach Party", duration: "3:45" },
        { title: "Positive Vibrations", duration: "6:32" },
        { title: "Reggae Roots", duration: "5:18" },
        { title: "Caribbean Dreams", duration: "4:45" },
        { title: "Unity Song", duration: "5:23" },
      ],
      reviews: [
        {
          user: "ReggaeFan",
          rating: 5,
          date: "2023-05-01",
          comment: "Pure positive vibes! This album brightens my day every time I listen to it.",
        },
        {
          user: "IslandGirl",
          rating: 4,
          date: "2023-05-15",
          comment: "Great reggae rhythms and uplifting messages. Perfect summer soundtrack!",
        },
      ],
    },
    {
      id: 12,
      title: "Synthwave Dreams",
      artist: "Retro Future",
      genre: "electronic",
      price: 8.99,
      releaseDate: "2023-06-15",
      cover: "/placeholder.svg?height=500&width=500",
      description:
        "A nostalgic synthwave album inspired by 80s electronic music and sci-fi soundtracks. Takes you on a journey through neon-lit cityscapes and digital dreams.",
      tracks: [
        { title: "Neon City", duration: "4:45" },
        { title: "Digital Dreams", duration: "5:23" },
        { title: "Retro Future", duration: "4:12" },
        { title: "Night Drive", duration: "6:32" },
        { title: "Cyber Punk", duration: "5:18" },
        { title: "Arcade Memories", duration: "4:56" },
        { title: "VHS Nostalgia", duration: "3:45" },
        { title: "Sunset Grid", duration: "5:32" },
      ],
      reviews: [
        {
          user: "SynthFan",
          rating: 5,
          date: "2023-06-30",
          comment:
            "This album perfectly captures that 80s synthwave vibe! Takes me back to a time I never actually experienced.",
        },
        {
          user: "RetroGamer",
          rating: 4,
          date: "2023-07-05",
          comment: "Great nostalgic sounds. 'Arcade Memories' is like the soundtrack to my childhood.",
        },
      ],
    },
  ],
}

